pyhf/pyhf-tutorial

book/introduction.md
**Squash and merge commit message**
```
* Update the LCG view used to LCG_98python3
- Uses Python 3.7 as runtime
```
=> fix: Update LCG view to LCG_98python3

.github/workflows/deploy-jupyter-book.yml, .pre-commit-config.yaml, README.md, binder/requirements.txt, book/HelloWorld.ipynb, book/Modifiers.ipynb, book/SerializationAndPatching.ipynb, book/SimpleWorkspace.ipynb, book/Toys.ipynb, book/UsingCalculators.ipynb, book/WorkspaceManipulations.ipynb, book/introduction.md
```
* Update to pyhf v0.6.2 and update API changes
- pyhf.simplemodels.hepdata_like -> pyhf.simplemodels.uncorrelated_background
- brazil.plot_results(ax, poi_values, results) -> brazil.plot_results(poi_values, results, ax=ax)
- Update URLs to point to v0.6.2
* Update number of published full statistical models to 8
- Change language from 'likelihoods' to 'statistical models' in keeping with upcoming white paper
* Update citation format
* Update pre-commit hooks
```
Resolves https://github.com/scikit-hep/pyhf/issues/1494
=> feat: Update tutorial to use pyhf v0.6.2

.github/workflows/deploy-jupyter-book.yml, .github/workflows/lint.yml, .pre-commit-config.yaml, README.md, binder/requirements.txt, book/HelloWorld.ipynb, book/Modifiers.ipynb, book/SerializationAndPatching.ipynb, book/SimpleWorkspace.ipynb, book/WorkspaceManipulations.ipynb, book/introduction.md
Addresses the tutorial part of https://github.com/scikit-hep/pyhf/issues/1578
```
* Update to pyhf v0.6.3 and update API changes
- with_aux -> include_auxdata
- Update URLs to point to v0.6.3
* Update pre-commit hooks
* Update to using Python 3.9
```
=> feat: Update tutorial to use pyhf v0.6.3

.github/workflows/deploy-jupyter-book.yml, .pre-commit-config.yaml, binder/postBuild, book/IntroToHiFa.ipynb, book/Modifiers.ipynb, book/SerializationAndPatching.ipynb, book/WorkspaceManipulations.ipynb
Update serialization and modifiers notebooks for [Publication of statistical models: hands-on workshop](https://indico.cern.ch/event/1088121/overview) pyhf session.
```
* Add Binder postBuild configuration file to install ROOT in Binder environment from Conda-forge
- Note this slows down the Binder build significantly as Conda is very slow to install ROOT
* Run CI in atlasamglab/stats-base:root6.24.06 Docker container to provide ROOT for serialization notebook
* Add ROOT execution to examples in WorkspaceManipulations notebook
* Add example use cases to all modifiers in Modifiers notebook
* Update number of published probability models to 18
* Add codespell pre-commit hook
```
=> feat: Update serialization and modifiers notebooks

book/_toc.yml, book/requirements.txt
```
* Update to Jupyter Book v0.12.1
* Migrate _toc.yml to use Jupyter Book v0.11+ syntax
- c.f. https://executablebooks.org/en/latest/updates/2021-06-18-update-toc.html
```
=> chore: Update to Jupyter Book v0.12.1

binder/postBuild
Significantly speed up installation of ROOT from conda-forge by using `mamba`. As [Binder already uses `mamba` for `repo2docker`](https://github.com/jupyterhub/repo2docker/pull/962) there is nothing extra to install. :) Thanks to @chrisburr for the advice here!
```
* Use mamba over conda for installation of ROOT in Binder postBuild
- Significantly improves speed of package solve and install
```
=> feat: Use mamba for installing packages from conda-forge

.github/workflows/deploy-jupyter-book.yml
Resolves #19 
```
* Deploy the Jupyter Book to either on push events (coming from merged PRs)
or from workflow dispatch triggers (to allow for redeployment on demand).
```
=> ci: Deploy Jupyter Book on workflow dispatch events

.pre-commit-config.yaml, README.md
```
* Add pre-commit.ci with pre-commit hook updates on a quarterly basis.
* Add pre-commit.ci status badge to README.
```
[![pre-commit.ci status](https://results.pre-commit.ci/badge/github/pyhf/pyhf-tutorial/main.svg)](https://results.pre-commit.ci/latest/github/pyhf/pyhf-tutorial/main)
=> ci: Add pre-commit.ci

.github/workflows/deploy-jupyter-book.yml, .github/workflows/lint.yml
```
* Update checkout action to v3
* Update setup-python to v3
- skipping v4 for 'Deploy Jupyter Book' for now given regression with containers
Co-authored-by: Matthew Feickert <matthew.feickert@cern.ch>
```
=> chore: Update GitHub Actions to latest releases

binder/postBuild
Without the `--yes` flag the mamba install will hang waiting for user input.
=> fix: Add '--yes' flag to mamba install

README.md, binder/requirements.txt, book/HelloWorld.ipynb, book/Modifiers.ipynb, book/SerializationAndPatching.ipynb, book/SimpleWorkspace.ipynb, book/WorkspaceManipulations.ipynb, book/introduction.md
Addresses the tutorial part of https://github.com/scikit-hep/pyhf/issues/2022
```
* Update to pyhf v0.7.0 and update API changes
- pyhf.infer.intervals.upperlimit -> pyhf.infer.intervals.upper_limits.upper_limit
- Update URLs to point to v0.7.0
```
=> feat: Bump to 0.7.0 API

.github/workflows/deploy-jupyter-book.yml
* Remove actions/setup-python GitHub Action in favor of using Python
supplied by container to avoid possible glibc version conflicts.
* Update image to atlasamglab/stats-base:root6.26.10.
=> ci: Use container Python over setting up with GitHub Actions

book/introduction.md
Modern versions of `jupyter-book` have switched to using `sphinx-design` so tab-set must be used over 'tabbed' directive.
- c.f. https://sphinx-design.readthedocs.io/en/latest/tabs.html
```
* Modern versions of jupyter-book have switched to using sphinx-design
so tab-set must be used over 'tabbed' directive.
- c.f. https://sphinx-design.readthedocs.io/en/latest/tabs.html
* Quote extras in introduction to improve install experience for users on
zsh.
```
=> fix: Use sphinx-design tab-set for tabs

.github/workflows/deploy-jupyter-book.yml, book/requirements.txt
```
* Update juptyer-book to v0.13.2 to be compatible with jsonschema requirements
of pyhf v0.7.0.
* Install binder/requirements.txt and book/requirements.txt at the same time to
force dependency resolution for both requirements files in the same environment.
```
=> feat: Update Jupyter Book to v0.13.2

book/Combinations.ipynb, book/SimpleWorkspace.ipynb, book/WorkspaceManipulations.ipynb
Resolves #33 
Amends PR #29 
```
* Update all APIs to be consistent with v0.7.0.
- Remove comment about making measurement on the fly with
`workspace.get_measurement` as no longer relevant.
- Remove all use of `workspace.parameters`, now
`workspace.model().config.parameters`, as the notebooks
are focusing on workspace attributes, not model config
attributes.
* Amends PR #29
```
=> fix: Update all APIs to pyhf v0.7.0

book/introduction.md
* Set the logo size to be reasonably centered in the page.
* Amends PR #45.
```
* Set the logo size by setting the width to be a percentage of the middle
page column width. Using a percentage allows for the image size to be
reactive to page adjustments and resizing.
* Amends PR https://github.com/pyhf/pyhf-tutorial/pull/45.
```
=> fix: Resize logo to fit page

.github/workflows/deploy-jupyter-book.yml
```
* Deploy the jupyter book website to GitHub Pages using GitHub Actions.
- actions/configure-pages
- actions/upload-pages-artifact
- actions/deploy-pages
```
=> ci: Deploy jupyter book with GitHub Pages action

.github/workflows/deploy-jupyter-book.yml, README.md, book/introduction.md, lite/jupyterlite.py, lite/jupytext.toml
```
* Add Pyodide build using JupyterLite.
* Split GitHub Pages build into a JupyterBook build and a Pyodide build and
require both to succeed and upload to deploy the website.
* Add jupyterlite.ipynb example notebook to guide users.
- Use jupytext to keep this as a .py file.
* Add WebAssembly live page link to introduction that opens to jupyterlite.ipynb.
* Add JupyterLite view badge to README.
Co-authored-by: Henry Schreiner <henry.fredrick.schreiner@cern.ch>
```
[![JupyterLite](https://jupyterlite.rtfd.io/en/latest/_static/badge.svg)](https://pyhf.github.io/pyhf-tutorial/live/lab/index.html?path=jupyterlite.ipynb)
Based on @henryiii's https://github.com/henryiii/level-up-your-python
=> ci: Add Pyodide build and JupyterLite based view

book/introduction.md
```
* Add recommendation to clone locally.
* Use `--channel conda-forge` in conda install example to ensure conda-forge is used.
* Use full name of pip flags for readability.
```
=> docs: Add instructions for local install to introduction

book/IntroToHiFa.ipynb
```
* Add further discussion of constraint terms and modifiers.
* Add links to other tools that use HistFactory.
* Add axis titles to plots.
```
=> feat: Expand discussion of constraints and modifiers in HistFactory Intro

README.md
* Remove last given notice from top of README.
* Update tutorial list with the summer school.
- c.f. https://indico.cern.ch/event/1293313/
=> docs: Add Computational HEP Traineeship Summer School 2023

README.md, binder/requirements.txt, book/HelloWorld.ipynb, book/Modifiers.ipynb, book/SerializationAndPatching.ipynb, book/SimpleWorkspace.ipynb, book/WorkspaceManipulations.ipynb, book/introduction.md, book/requirements.lock, lite/jupyterlite.py
* Update to pyhf v0.7.3.
- Update URLs to point to v0.7.3.
* Update requirements.txt and upgrade lock file.
- Using 'pip-compile --generate-hashes --upgrade-package pyhf'
Part of https://github.com/scikit-hep/pyhf/issues/2289
=> feat: Update to pyhf v0.7.3

book/_config.yml
* Resolves #60 
* Resolves #13 
To allow for long running processes that require actual computation extend the notebook cell timeout from the default 30 seconds to 120 seconds (2 minutes).
- c.f. https://jupyterbook.org/en/stable/customize/config.html
```
* To allow for long running processes that require actual computation
extend the notebook cell timeout from the default 30 seconds to 120
seconds (2 minutes).
- c.f. https://jupyterbook.org/en/stable/customize/config.html
```
=> fix: Set notebook cell timeout to 2 minutes

book/Toys.ipynb
Resolves #63 
* Use the correct model (`model_low`) for demonstration of the difference between the asymptotics based and toy based calculators.
- Amends PR https://github.com/pyhf/pyhf-tutorial/pull/1
* Use 5000 pseudo-experiments to demonstrate the difference more effectively.
* Use underscores in numeric literals (5_000) for better readability.
- c.f. https://peps.python.org/pep-0515/
```
* Use the correct model (`model_low`) for demonstration of the
difference between the asymptotics based and toy based calculators.
- Amends PR https://github.com/pyhf/pyhf-tutorial/pull/1
* Use 5000 pseudo-experiments to demonstrate the difference more
effectively.
* Use underscores in numeric literals (5_000) for better readability.
- c.f. https://peps.python.org/pep-0515/
```
=> fix: Use correct model for low stats demonstration

book/_config.yml
* Update cell timeout to 210 seconds to allow for sufficient time for the pseudo-experiments to run in book/Toys.ipynb.
=> fix: Update notebook cell timeout for toys notebook

README.md, binder/requirements.txt, book/HelloWorld.ipynb, book/Modifiers.ipynb, book/SerializationAndPatching.ipynb, book/SimpleWorkspace.ipynb, book/WorkspaceManipulations.ipynb, book/introduction.md, book/requirements.lock, lite/jupyterlite.py
* Update to pyhf v0.7.4.
- Update URLs to point to v0.7.4.
* Update requirements.txt and upgrade lock file.
- Using 'pip-compile --generate-hashes --upgrade-package pyhf'
=> feat: Update to pyhf v0.7.4

README.md, binder/requirements.txt, book/HelloWorld.ipynb, book/Modifiers.ipynb, book/SerializationAndPatching.ipynb, book/SimpleWorkspace.ipynb, book/WorkspaceManipulations.ipynb, book/introduction.md, book/requirements.lock, lite/jupyterlite.py
* Update to pyhf v0.7.5.
- Update URLs to point to v0.7.5.
* Update requirements.txt and upgrade lock file.
- Using 'pip-compile --generate-hashes --upgrade-package pyhf'
=> feat: Update pyhf to v0.7.5

.github/workflows/deploy-jupyter-book.yml, .github/workflows/lint.yml, binder/postBuild, binder/runtime.txt
```
* Update GitHub Actions.
- actions/checkout@v3 -> actions/checkout@v4
- actions/setup-python@v4 -> actions/setup-python@v5
* Use prefix-dev/setup-pixi to setup pixi and load environment.
- Remove use of ROOT Docker image.
* Use pixi commands to build Jupyter book
- This significantly speeds up the build in CI by multiple minutes.
* Use uvx for lint workflow.
* Use root_base in Binder postBuild.
* Update Binder Python to 3.12.
```
=> ci: Use pixi for book build

book/introduction.md
* Demonstrate installing the 'jax' extra instead of 'tensorflow'.
=> docs: Switch TensorFlow example for JAX

.github/dependabot.yml, .github/workflows/deploy-jupyter-book.yml
* actions/upload-artifact v3 -> v4.
* actions/download-artifact v3 -> v4.
* actions/configure-pages v2 -> v5.
* actions/upload-pages-artifact v2 -> v3.
* actions/deploy-pages v1 -> v4.
* Add Dependabot config for monthly GitHub Actions updates.
=> ci: Update GitHub actions and add Dependabot config

.github/workflows/deploy-jupyter-book.yml, pixi.lock, pixi.toml
Resolves #87 
```
* Add jupyterlite-pyodide-kernel to install for pyodide build.
- jupyterlite-pyodide-kernel had been removed from dependencies of jupyterlite.
* Add jupyterlite pixi environment.
- Add jupyterlite environment with dependencies and tasks that allow for building
and serving of the jupyterlite pages locally.
```
=> fix: Add jupyterlite-pyodide-kernel dependency 

README.md
* 'uv pip compile' is the tool used to build the requirements.lock lock file.
- Amends PR https://github.com/pyhf/pyhf-tutorial/pull/86.
=> docs: Note 'uv pip compile' is tool used

pixi.lock, pixi.toml
* Update jupyterlite feature to use jupyterlite v0.5.0 for better handling of kernel restarts.
- c.f. https://github.com/jupyterlite/jupyterlite/releases/tag/v0.5.0
* Add depends-on for build-lite to serve and add caching inputs and outputs for build-lite.
```
* Update jupyterlite feature to use jupyterlite v0.5.0 for better handling
of kernel restarts.
- c.f. https://github.com/jupyterlite/jupyterlite/releases/tag/v0.5.0
* Add depends-on for build-lite to serve and add caching inputs and outputs
for build-lite.
```
=> chore: Update jupyterlite

.github/dependabot.yml, CODEOWNERS
* Add `CODEOWNERS` file to add reviewers as Dependabot reviewers configuration option is being removed.
- c.f. https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/
- c.f. https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-file-location
=> chore: Add CODEOWNERS file
